#pragma once

// Centralized libmpv include to gracefully fall back to a local stub when the
// native dependency bundle has not been prepared yet (e.g. in IDE-only setups).
// The stub ships the official libmpv client header so compilation keeps
// working until the real dependency prefix is generated by the build scripts.
#if defined(__has_include)
#  if __has_include(<mpv/client.h>)
#    include <mpv/client.h>
#  else
#    include "stubs/mpv/client.h"
#  endif
#else
#  include <mpv/client.h>
#endif
